name: Entur/Meta/CloudAuth
description: Authenticate with cloud provider
inputs:
  environment:
    description: "GitHub environment to use Google Cloud: (dev, tst, prd) or Azure: (az-dev, az-test, az-prod)"
    required: true
  cloud_provider:
    description: "Which cloud service provider to use - Google Cloud: 'gcp' or Azure: 'az'"
    default: "gcp"
  gcp_workload_identity_provider:
    description: "Workload identity provider to use for authentication against Google Cloud"
  gcp_service_account:
    description: "Service account to use for authentication towards Google Cloud"
  azure_client_id:
    description: "Azure client ID"
  azure_tenant_id:
    description: "Azure tenant ID"
  azure_subscription_id:
    description: "Azure subscription ID"
runs:
  using: "composite"
  steps:
    - id: verify-cloud-provider
      if: inputs.cloud_provider != 'gcp' && inputs.cloud_provider != 'az'
      shell: bash
      env:
        GHA_CLOUD_AUTH_CLOUD_PROVIDER: ${{ inputs.cloud_provider }}
      run: |
        echo "Invalid cloud provider input: ${GHA_CLOUD_AUTH_CLOUD_PROVIDER}"
        echo "Valid options are: 'gcp' or 'az'"
        exit 1
    - id: verify-vars-is-set-gcp
      name: Verify GCP environment variables
      if: inputs.cloud_provider == 'gcp' && (inputs.gcp_workload_identity_provider == '' || inputs.gcp_service_account == '')
      shell: bash
      run: |
        echo "Missing required environment variables"
        echo "Verify that 'workload_identity_provider' and 'service_account' are set and you are using the correct environment name"
        exit 1
    - id: verify-vars-is-set-az
      name: Verify Azure environment variables
      if: inputs.cloud_provider == 'az' && (inputs.azure_client_id == '' || inputs.azure_tenant_id == '' || inputs.azure_subscription_id == '')
      shell: bash
      run: |
        echo "Missing required environment variables"
        echo "Verify that 'azure_client_id','azure_tenant_id' and 'azure_subscription_id' are set and you are using the correct environment name"
        exit 1
    - id: verify-branch-repository-name
      name: Verify branch and repo name does not exceed 127 characters
      shell: bash
      run: |
        BRANCH_REPO=$(echo "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}")
        echo $BRANCH_REPO
        if [ "${#BRANCH_REPO}" -gt 127 ]; then
          echo "ERROR: The combination of Repository and Branch name is too long, reduce the length of the branch name."
          exit 1
        fi
    - id: login-gcp
      name: Authenticate with Google Cloud
      if: inputs.cloud_provider == 'gcp'
      uses: google-github-actions/auth@v2.1.2
      with:
        workload_identity_provider: ${{ inputs.gcp_workload_identity_provider }}
        service_account: ${{ inputs.gcp_service_account }}
    - id: login-azure
      name: Authenticate with Azure
      if: inputs.cloud_provider == 'az'
      uses: Azure/login@v2
      with:
        client-id: ${{ inputs.azure_client_id }}
        tenant-id: ${{ inputs.azure_tenant_id }}
        subscription-id: ${{ inputs.azure_subscription_id }}
