name: Entur/Meta/DockerAuth
description: Authenticate with Docker registry
inputs:
  environment:
    description: "GitHub environment to use Google Cloud: (dev, tst, prd) or Azure: (az-dev, az-test, az-prod)"
    default: "prd"
  cloud_provider:
    description: "Which cloud service provider to use - Google Cloud: 'gcp' or Azure: 'az'"
    default: "gcp"
  token_format:
    description: |-
      Output format for the generated authentication token. For OAuth 2.0 access
      tokens, specify "access_token". For OIDC tokens, specify "id_token". To
      skip token generation, leave this value empty.
    default: "access_token"
  workload_identity_provider:
    description: "Workload identity provider to use for authentication"
  service_account:
    description: "Service account to use for authentication"
  azure_client_id:
    description: Azure client ID
  azure_tenant_id:
    description: Azure tenant ID
  azure_subscription_id:
    description: "Azure subscription ID"

runs:
  using: "composite"
  steps:
    - id: verify-cloud-provider
      if: inputs.cloud_provider != 'gcp' && inputs.cloud_provider != 'az'
      shell: bash
      env:
        GHA_CLOUD_AUTH_CLOUD_PROVIDER: ${{ inputs.cloud_provider }}
      run: |
        echo "Invalid cloud provider input: ${GHA_CLOUD_AUTH_CLOUD_PROVIDER}"
        echo "Valid options are: 'gcp' or 'az'"
        exit 1
    - id: verify-vars-is-set-gcp
      name: Verify GCP environment variables
      if: inputs.cloud_provider == 'gcp' && (inputs.workload_identity_provider == '' || inputs.service_account == '')
      shell: bash
      run: |
        echo "Missing required environment variables"
        echo "Verify that 'workload_identity_provider' and 'service_account' are set and you are using the correct environment name"
        exit 1
    - id: verify-vars-is-set-az
      name: Verify GCP environment variables
      if: inputs.cloud_provider == 'az' && (inputs.azure_client_id == '' || inputs.azure_tenant_id == '' || inputs.azure_subscription_id == '')
      shell: bash
      run: |
        echo "Missing required environment variables"
        echo "Verify that 'azure_client_id','azure_tenant_id' and 'azure_subscription_id' are set and you are using the correct environment name"
        exit 1
    - id: login-gcp
      name: Authenticate with Google Cloud
      if: inputs.cloud_provider == 'gcp'
      uses: google-github-actions/auth@v2.1.2
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}
        token_format: ${{ inputs.token_format }}
    - id: login-gcr
      name: Authenticate with Google Container Registry
      uses: docker/login-action@v3.1.0
      if: inputs.cloud_provider == 'gcp'
      with:
        registry: eu.gcr.io
        username: oauth2accesstoken
        password: ${{ steps.login-gcp.outputs.access_token }}
    - id: login-azure
      name: Authenticate with Azure
      if: inputs.cloud_provider == 'az'
      uses: Azure/login@v2
      with:
        client-id: ${{ inputs.azure_client_id }}
        tenant-id: ${{ inputs.azure_tenant_id }}
        subscription-id: ${{ inputs.azure_subscription_id }}
    - id: login-acr
      name: Authenticate with Azure Container Registry
      if: inputs.cloud_provider == 'az'
      shell: bash
      run: |
        az acr login --name acrentur001
