name: Verify PR

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  workflow_call:

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: read
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
