name: Verify PR

on:
  pull_request:
  workflow_call:

jobs:
  verify-pr:
    name: Ensure PR title complies with conventional commit conventions
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: read
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: true
